/* Stub header for TAS2560 driver */
#ifndef _MSM_PCM_ROUTING_H
#define _MSM_PCM_ROUTING_H

#define LPASS_BE_PRI_I2S_RX "PRIMARY_I2S_RX"
#define LPASS_BE_PRI_I2S_TX "PRIMARY_I2S_TX"
#define LPASS_BE_MI2S_RX "MI2S_RX"
#define LPASS_BE_MI2S_TX "MI2S_TX"
#define LPASS_BE_QUAT_MI2S_RX "QUAT_MI2S_RX"
#define LPASS_BE_QUAT_MI2S_TX "QUAT_MI2S_TX"
#define LPASS_BE_SEC_MI2S_RX "SEC_MI2S_RX"
#define LPASS_BE_SEC_MI2S_TX "SEC_MI2S_TX"
#define LPASS_BE_PRI_MI2S_RX "PRI_MI2S_RX"
#define LPASS_BE_PRI_MI2S_TX "PRI_MI2S_TX"
#define LPASS_BE_TERT_MI2S_RX "TERTIARY_MI2S_RX"
#define LPASS_BE_TERT_MI2S_TX "TERTIARY_MI2S_TX"
#define LPASS_BE_QUIN_MI2S_RX "QUINARY_MI2S_RX"
#define LPASS_BE_QUIN_MI2S_TX "QUINARY_MI2S_TX"
#define LPASS_BE_SLIMBUS_0_RX "SLIMBUS_0_RX"
#define LPASS_BE_SLIMBUS_0_TX "SLIMBUS_0_TX"
#define LPASS_BE_HDMI "HDMI"
#define LPASS_BE_INT_BT_SCO_RX "INT_BT_SCO_RX"
#define LPASS_BE_INT_BT_SCO_TX "INT_BT_SCO_TX"

#endif

/* Backend DAI IDs */
enum {
    MSM_BACKEND_DAI_PRI_I2S_RX = 0,
    MSM_BACKEND_DAI_PRI_I2S_TX,
    MSM_BACKEND_DAI_SEC_I2S_RX,
    MSM_BACKEND_DAI_SEC_I2S_TX,
    MSM_BACKEND_DAI_TERT_I2S_RX,
    MSM_BACKEND_DAI_TERT_I2S_TX,
    MSM_BACKEND_DAI_QUAT_I2S_RX,
    MSM_BACKEND_DAI_QUAT_I2S_TX,
    MSM_BACKEND_DAI_QUIN_I2S_RX,
    MSM_BACKEND_DAI_QUIN_I2S_TX,
    MSM_BACKEND_DAI_MI2S_RX = MSM_BACKEND_DAI_QUIN_I2S_RX,
    MSM_BACKEND_DAI_MI2S_TX = MSM_BACKEND_DAI_QUIN_I2S_TX,
    MSM_BACKEND_DAI_QUINARY_MI2S_RX = MSM_BACKEND_DAI_QUIN_I2S_RX,
    MSM_BACKEND_DAI_QUATERNARY_MI2S_RX = MSM_BACKEND_DAI_QUAT_I2S_RX,
    MSM_BACKEND_DAI_MAX,
};

#endif
